### ISSUE TITLE
question: monkey patch

### ISSUE THREAD

**Issue by fabienjuif** [ptitFicus/naive-router#74]
I have a question about your "monkey patch" in the window global variable.
Why do you do : 
```
https://github.com/ptitFicus/naive-router/blob/master/src/Route.js#L19
```

1. First solution I would think of:  Instanciating the event queue before exporting it?
2. Second solution I would think of: Instanciating the event queue in "Route" module (`Route.js`)?

Maybe I forgot something?
Do you fear the import mechanism to instanciate twice the modules?

**Comment by ptitFicus** [comment]
You're right, not sure why I did that ...
I think I'll go with your first solution, thanks !
