### ISSUE TITLE
Components are "Anonymous" in react-devtools

### ISSUE THREAD

**Issue by fabienjuif** [ptitFicus/naive-router#80]
Maybe this is on my side, I just see that naive-router components are "Anonymouse" in the devtools:

![image](https://user-images.githubusercontent.com/17828231/64591860-0b105980-d3ab-11e9-888f-43fb2474c6c2.png)

**Comment by ptitFicus** [comment]
This is indeed annoying, I don't understand. I'm gonna investigate on this one.
